### ISSUE TITLE
Document whether public API arguments are optional / required 

### ISSUE THREAD

**Issue by m-mujica** [canjs/can-value#25]
I ran into some issues with the following code:

```
canValue.bind(defineMapInstance)
```

Seems like `keyPath` is not optional for `canValue.bind`, it'd help a lot if the docs make that clear, specially since some of the methods might work with single value observables.

**Comment by justinbmeyer** [comment]
In CanJS, every param should be considered required unless it is explicitly stated as optional.

https://canjs.com/doc/can-value.bind.html

Do any of the methods work as single value observables?

**Comment by m-mujica** [comment]
I'm going to close this issue:

a) You can assume the arguments are required, otherwise they are labeled as optional in the docs

b) Using the public API methods of `can-value` with "single values" does not really make any sense, since the parent can't change it at that point anyway.

For instance:

```javascript
someFunction() {
  new Comp({
    viewModel: { prop: value.with(string) }
  });
}
```

using `value.with` in this example makes no sense, since the VM owning `someFunction` cannot change `string`. In other words there is nothing listening to the changes of the observation returned by `value.with(string)`.

It might make sense in the following example: 

```javascript
someFunction() {
  var prop = value.with(string);
  this.listenTo(prop, () => { DO_SOMETHING })
  new Comp({viewModel: {prop: prop }})
}
```

but don't write it like this, there is probably a better way. If `string` is a property of the viewmodel, the right way to do it would be:

```javascript
someFunction() {
  new Comp({
    viewModel: { prop: value.from(this, 'string') }
  });
}
```
